### PR TITLE
Added more end-points

### PR DESCRIPTION
**Pull request by jonasfj**

### CODE REVIEW

**Comment by gregarndt** [comment]
looks good.  Probably need to create a new proxy image, then deploy a new worker

**Comment by jonasfj** [comment]
I'm mergining.. I assume tests a broken because of revoked credentials...

**Comment by jonasfj** [comment]
@petemoore, please let me know if you see anything wrong here...

**Comment by petemoore** [comment]
looks reasonable!

**Comment by petemoore** [comment]
> I'm mergining.. I assume tests a broken because of revoked credentials...

The broken test is due to the endpoint `/client/<clientId>/scopes` no longer being available.

The returned HTTP body is:

```
Cannot GET /v1/client/<clientId>/scopes?bewit=<bewit>
```

which causes `invalid character 'C' looking for beginning of value` when trying to parse it as json. I'll push a fix to include the HTTP Response in the error message.

**Comment by petemoore** [comment]
Probably taskcluster-proxy tests should use taskcluster-client-go rather than hardcoded implementations of the references/schemas, which change over time.

**Comment by petemoore** [comment]
I've fixed the last broken test now! \o/

**Pull request merged**
