### PR TITLE
Reduce docker image size

### PR DESCRIPTION
**Pull request by petemoore**
This reduces docker image size by ..... 97% !! :-)

(223.6 MB -> 6.9 MB)

### CODE REVIEW

**Comment by djmitche** [comment]
Can you do the same for relengapi proxy?

**Comment by petemoore** [comment]
Yes, I tested locally, and the proxy runs fine.

**Comment by petemoore** [comment]
@djmitche 

```
pmoore@Petes-iMac:~/go/src/github.com/taskcluster/taskcluster-proxy reduce-docker-image-size $ ./build.sh taskcluster/taskcluster-proxy:3.0.9
Generating ca certs using latest ubuntu version...
Sending build context to Docker daemon 9.726 MB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:latest
latest: Pulling from ubuntu
58488e45273c: Already exists 
25810b66099e: Already exists 
6571ba684f54: Already exists 
6ed49a73d8f0: Already exists 
c53777cbfc31: Already exists 
56465e1e45d2: Already exists 
Digest: sha256:312986132029d622ae65423ca25d3a3cf4510de25c47b05b6819d61e2e2b5420
Status: Image is up to date for ubuntu:latest
 ---> 56465e1e45d2
Step 1 : RUN apt-get update
 ---> Using cache
 ---> 68341eead114
Step 2 : RUN apt-get install -y ca-certificates
 ---> Using cache
 ---> 02befbbb9d17
Successfully built 02befbbb9d17
1476470490
Building proxy server...
Building docker image for proxy server
Sending build context to Docker daemon 9.726 MB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 
Step 1 : EXPOSE 80
 ---> Using cache
 ---> b1713210c2d0
Step 2 : COPY target/taskcluster-proxy /taskcluster-proxy
 ---> d822cee8d9fa
Removing intermediate container ed9c70237edd
Step 3 : COPY target/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
 ---> f3f2ed6b6c3e
Removing intermediate container d6dfb00d6809
Step 4 : ENTRYPOINT /taskcluster-proxy --port 80
 ---> Running in 8ad14752e89a
 ---> b655e51451d3
Removing intermediate container 8ad14752e89a
Successfully built b655e51451d3
pmoore@Petes-iMac:~/go/src/github.com/taskcluster/taskcluster-proxy reduce-docker-image-size $ docker run taskcluster/taskcluster-proxy:3.0.9 --client-id "${TASKCLUSTER_CLIENT_ID}" --access-token "${TASKCLUSTER_ACCESS_TOKEN}" FMX65e2OQ7eDasrqQhIr8A
2016/10/14 18:41:44 clientId: 'mozilla-ldap/pmoore@mozilla.com/dev'
accessToken: 'vwKyk-NkTQi71-caeAhnKQzsO8bS_HRp6zCEKwpp1KRQ'
certificate: ''
2016/10/14 18:41:44 Warning - no taskcluster certificate set - assuming permanent credentials are being used
2016/10/14 18:41:45 Proxy with scopes:  [secrets:get:project/taskcluster/gecko/hgfingerprint docker-worker:relengapi-proxy:tooltool.download.public docker-worker:relengapi-proxy:tooltool.download.internal secrets:get:project/releng/gecko/build/level-1/* docker-worker:cache:level-1-hg-shared docker-worker:cache:level-1-checkouts docker-worker:cache:tooltool-cache]
```

The fact it shows the scopes, means it was able to use the cacerts to talk to the queue - so the go program works and the certs are present and usable.

If you merge, I can publish the docker image.

It is ~9pm on Friday evening, so I think I won't be able to tackle relengapi proxy until I'm back in a week after PTO. But happy to do it - feel free to create a bug / issue or something for me.

**Comment by jhford** [comment]
I'm not 100% sure yet, but something related to this pull request seems to have triggered https://bugzilla.mozilla.org/show_bug.cgi?id=1310561 which manifests as PUT requests being rewritten to GET requests.  I've reverted the docker hub tags so that `latest` and `3.0.10` now refer to the same image that `3.0.8` does, which was the last known good version of the image.

**Comment by petemoore** [comment]
> I'm not 100% sure yet, but something related to this pull request seems to have triggered https://bugzilla.mozilla.org/show_bug.cgi?id=1310561 which manifests as PUT requests being rewritten to GET requests.  I've reverted the docker hub tags so that `latest` and `3.0.10` now refer to the same image that `3.0.8` does, which was the last known good version of the image.

Indeed it did. :-(

See https://bugzilla.mozilla.org/show_bug.cgi?id=1310643#c12 for the details. This will be fixed in a subsequent PR.

**Pull request merged**
